* First lesson in C programming

Essentially, the whole lesson consisted of people desperately trying to get their IDEs to work and GCC to compile under Windows.
Thankfully, I am an egotistical Ubuntu user who has ==gcc== already installed. All it took is a small line of emacs dotfile configuration.

#+BEGIN_SRC emacs-lisp
(defun gcc-compile ()
"quick compilation using gcc"
(compile (concat "gcc -Wall -pedantic -ggdb -o test " buffer-file-name " -lm"))) ; -lm is a default c math library.

;; to set the key without possibly overriding anything, use global-set-key.
;; emacs is kinda weird since they have four levels of privilege when it comes to keybinds.
(global-set-key (kbd "C-c k") '(lambda () (interactive) (gcc-compile)))
#+END_SRC

As you can see, this set up is a bit clunky, because linking libraries is done by editing the dotfile. A way better method is to set up ==make== or ==cmake== to take care of the build process, but oh well.
In the end, editing the dotfile is in a way working with a makefile, more or less.

I also suggest installing spacemacs because it is less bare-bone than the default editor and has some nice features too.

No actual C files were supposed to be produced that day.
